"""Altered tables

Revision ID: 08df6c177ea3
Revises: 4d8a11614602
Create Date: 2025-01-03 09:27:55.604691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08df6c177ea3'
down_revision = '4d8a11614602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumed_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumed_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumed_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('consumed_count')

    with op.batch_alter_table('consumed_logs', schema=None) as batch_op:
        batch_op.drop_column('consumed_count')

    # ### end Alembic commands ###
